apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: projectB
  namespace: default
spec:
  rules:
    - host: default.projectB.com
      http:
        paths:
          - path: /
            backend:
              serviceName: projectB
              servicePort: 8080